---

- hosts: adminserver

  tasks:
  
    - name: print message using debug
      debug: 
        msg: "Hello we are leaving Ansible"

    - debug:
        msg: "Hello ketan"

  vars:
    name: Arpita
    lastname: Naik

  tasks:

    - debug: 
        msg: "user name is {{ name }}"

    - debug: 
        msg: " My os is {{  ansible_distribution }}"

    - debug:
        msg: "my python version is {{ ansible_python_version }}"    
