---

- hosts: adminserver
  become: yes

  tasks: 
   - name: Install apache pkg
       yum: 
         name: httpd
         state: present
         use_backend: dnf


   - name: state apache service
       systemd:
         name: httpd
         state: started
         enabled: yes



